# Generated by Django 5.0.6 on 2024-09-19 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="organizer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="events",
                to="events.organizer",
            ),
        ),
    ]
