# Generated by Django 5.0.6 on 2024-09-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_event_latitude_event_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="is_organizer",
            field=models.BooleanField(default=False),
        ),
    ]
