# Generated by Django 5.0.6 on 2024-09-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_event_participants_usermodel_balance_promocode_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="location",
        ),
        migrations.AddField(
            model_name="event",
            name="age",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="image",
            field=models.ImageField(default=None, upload_to=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="sex",
            field=models.CharField(
                choices=[("male", "Мужской"), ("female", "Женский")],
                default="female",
                max_length=6,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="source",
            field=models.URLField(default="https://example.com"),
            preserve_default=False,
        ),
    ]
