# Generated by Django 5.0.6 on 2024-09-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_event_location_event_age_event_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="type",
            field=models.CharField(
                choices=[("news", "Новости"), ("event", "Мероприятия")],
                default="news",
                max_length=5,
            ),
            preserve_default=False,
        ),
    ]
