# Generated by Django 5.0.6 on 2024-09-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
