# Generated by Django 5.0.6 on 2024-09-18 17:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organizer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organization_name", models.CharField(max_length=255)),
                (
                    "ogrn",
                    models.CharField(
                        max_length=13,
                        validators=[django.core.validators.RegexValidator("^\\d{13}$")],
                    ),
                ),
                ("documents", models.FileField(upload_to="org_docs/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (
                                "WaitingForConfirmation",
                                "Ожидает проверки администратором",
                            ),
                            ("Confirmed", "Проверенна организатором"),
                            ("Rejected", "Отклоненно администратором"),
                        ],
                        default="WaitingForConfirmation",
                        max_length=50,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Организатор",
                "verbose_name_plural": "Организаторы",
            },
        ),
    ]
